services:
  basis-server:
    image: 'ghcr.io/basisvr/basis-server:nightly'
    container_name: basis-server
    init: true
    restart: unless-stopped
    environment:
      SetPort: 4296
      HealthCheckPort: 10666
      PromethusPort: 1234
      PeerLimit: 1024
      EnableStatistics: true
      EnableConsole: false
    ports:
      - '4296:4296/udp'
      - '10666:10666/tcp'
      - '1234:1234/tcp'
      - '4000:4000/tcp'
    volumes:
      - './initialresources:/app/initialresources:ro'
      - './config:/app/config'
      - './logs:/app/logs'
    healthcheck:
      test:
        - CMD
        - curl
        - '-f'
        - 'http://localhost:10666/health'
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 2s

  marusansi-basis-dashboard:
    build:
      context: 'https://github.com/nodokaha/MarusansiBasisDashboard.git#main'
    container_name: dashboard
    restart: unless-stopped
    network_mode: "service:basis-server"
    depends_on:
      basis-server:
        condition: service_healthy
